Fix return type in get_invalid_systemwide_thread_id
The build fails on AIX with the following error:
```
include/boost/interprocess/detail/os_thread_functions.hpp: In function 'boost::interprocess::ipcdetail::OS_systemwide_thread_id_t boost::interprocess::ipcdetail::get_invalid_systemwide_thread_id()':
include/boost/interprocess/detail/os_thread_functions.hpp:375:12: error: 'thread_t' was not declared in this scope; did you mean 'boost::asio::execution::detail::mapping::thread_t'?
  375 | {  return (thread_t)(-1);  }
      |            ^~~~~~~~
      |            boost::asio::execution::detail::mapping::thread_t
```
It seems that this is caused by a copy paste error from the Solaris implementation in     
https://github.com/boostorg/interprocess/commit/bfce9f1e0b5220384c4f4a320775ab9d542d54f6